"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import type { ReactNode } from "react";
import { ArrowRight, Award, BookOpenCheck, BriefcaseBusiness, Check, ChevronDown, Code2, Layers3, MessageCircleHeart, Rocket, ShieldCheck, Sparkles, UsersRound, type LucideIcon } from "lucide-react";

const features: [LucideIcon, string, string][] = [
  [Code2, "Build for real", "Ship practical work on live-project briefs—not classroom exercises."],
  [UsersRound, "Mentors in your corner", "Get thoughtful feedback and clear direction from working professionals."],
  [Award, "Proof of progress", "Earn a verified completion certificate and a portfolio you can show."],
];
const faqs = [
  ["Who can apply?", "Students and recent graduates with a curiosity for software development can apply. You do not need prior professional experience."],
  ["How much time does it require?", "Plan for 10–12 focused hours a week across the eight-week program, including mentor sessions and project work."],
  ["Will I receive a certificate?", "Yes. Successful participants receive a verifiable InternLaunch completion certificate and project feedback summary."],
  ["Is the internship remote?", "Yes, the program is fully remote. You will collaborate in the tools modern product teams use every day."],
];
const benefits: [LucideIcon, string][] = [[BriefcaseBusiness, "Live project exposure"], [BookOpenCheck, "Structured learning path"], [MessageCircleHeart, "Dedicated mentor support"], [ShieldCheck, "Recognized certificate"]];

const rise = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };

export function LandingPage() {
  return <main className="overflow-hidden">
    <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-20 sm:pt-28 lg:px-8 lg:pb-28">
      <div className="absolute right-[-7rem] top-4 -z-10 size-96 rounded-full bg-blue-500/15 blur-3xl" />
      <div className="grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
        <motion.div initial="hidden" animate="show" transition={{ staggerChildren: .12 }}>
          <motion.div variants={rise} className="inline-flex items-center gap-2 rounded-full border border-blue-400/20 bg-blue-400/10 px-3 py-1.5 text-xs font-medium text-blue-300"><Sparkles className="size-3.5" /> Applications open for the 2026 cohort</motion.div>
          <motion.h1 variants={rise} className="mt-6 max-w-3xl text-4xl font-semibold leading-[1.08] tracking-tight text-white sm:text-6xl">Your career deserves a <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-300 to-cyan-300">stronger start.</span></motion.h1>
          <motion.p variants={rise} className="mt-6 max-w-xl text-lg leading-8 text-slate-300">A hands-on software development internship designed to turn your potential into real experience, real projects, and real confidence.</motion.p>
          <motion.div variants={rise} className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/apply" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-500 px-5 py-3 text-sm font-semibold text-white shadow-xl shadow-blue-500/25 transition hover:-translate-y-0.5 hover:bg-blue-400">Start your application <ArrowRight className="size-4" /></Link><Link href="/internship" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/12 bg-white/4 px-5 py-3 text-sm font-semibold text-slate-100 transition hover:bg-white/8">Explore the program</Link></motion.div>
          <motion.div variants={rise} className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-400"><span className="flex items-center gap-2"><Check className="size-4 text-blue-400"/> No prior experience needed</span><span className="flex items-center gap-2"><Check className="size-4 text-blue-400"/> Fully remote</span></motion.div>
        </motion.div>
        <motion.div initial={{ opacity: 0, scale: .95, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .65, delay: .2 }} className="relative mx-auto w-full max-w-lg rounded-3xl border border-white/12 bg-gradient-to-br from-white/10 to-white/[.02] p-4 shadow-2xl shadow-blue-950/40 backdrop-blur">
          <div className="rounded-2xl border border-white/10 bg-[#101a30] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-blue-300">InternLaunch dashboard</p><p className="mt-1 text-lg font-semibold">Your learning sprint</p></div><div className="grid size-11 place-items-center rounded-xl bg-blue-500/15 text-blue-300"><Rocket className="size-5"/></div></div><div className="mt-8 grid grid-cols-3 gap-3">{[["8", "weeks"],["3", "live briefs"],["1:1", "support"]].map(([big, small]) => <div key={small} className="rounded-xl border border-white/8 bg-white/[.035] p-3"><p className="text-xl font-semibold text-white">{big}</p><p className="mt-1 text-xs text-slate-400">{small}</p></div>)}</div><div className="mt-5 rounded-xl border border-blue-400/15 bg-blue-500/8 p-4"><div className="flex items-center justify-between text-sm"><span className="font-medium">Product build sprint</span><span className="text-blue-300">Week 3 of 8</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/8"><motion.div initial={{ width: 0 }} animate={{ width: "42%" }} transition={{ delay: .8, duration: .8 }} className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-400" /></div></div><div className="mt-5 flex items-center gap-3"><div className="flex -space-x-2">{["AS","RK","SM"].map((i, n) => <span key={i} className={`grid size-8 place-items-center rounded-full border-2 border-[#101a30] text-[10px] font-bold ${n === 1 ? "bg-violet-500" : n === 2 ? "bg-cyan-500" : "bg-blue-500"}`}>{i}</span>)}</div><span className="text-xs text-slate-400">Collaborate with a motivated cohort</span></div></div>
          <div className="absolute -bottom-5 -left-4 rounded-xl border border-white/10 bg-[#18243d]/95 px-4 py-3 shadow-xl backdrop-blur"><p className="text-[11px] text-slate-400">Portfolio confidence</p><p className="mt-1 text-sm font-semibold"><span className="text-emerald-400">+85%</span> on average</p></div>
        </motion.div>
      </div>
    </section>

    <section id="program" className="border-y border-white/7 bg-[#0d1629]/70"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-y-7 px-5 py-8 text-center sm:grid-cols-4 lg:px-8">{[["1,200+","students launched"],["4.9/5","learner rating"],["8 weeks","structured growth"],["100%","remote-friendly"]].map(([a,b]) => <div key={b}><p className="text-xl font-semibold text-white">{a}</p><p className="mt-1 text-xs text-slate-400">{b}</p></div>)}</div></section>

    <Section eyebrow="Why InternLaunch" title="A launchpad built around doing." copy="Everything is intentionally designed to make your first professional chapter feel less uncertain—and far more achievable."><div className="grid gap-5 md:grid-cols-3">{features.map(([Icon,title,copy], i) => <motion.article initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i*.1 }} key={title as string} className="rounded-2xl border border-white/9 bg-white/[.035] p-6 transition hover:-translate-y-1 hover:border-blue-400/30 hover:bg-white/[.055]"><div className="grid size-11 place-items-center rounded-xl bg-blue-500/12 text-blue-300"><Icon className="size-5" /></div><h3 className="mt-5 text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></motion.article>)}</div></Section>

    <Section id="how-it-works" eyebrow="Simple by design" title="From application to momentum in four clear steps."><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[["01","Apply in minutes","Tell us about your interests and goals."],["02","Get welcomed in","Receive your program access and cohort details."],["03","Build with guidance","Work through live briefs with mentors nearby."],["04","Show what you’ve made","Leave with polished proof of your progress."]].map(([num,title,copy]) => <div key={num} className="relative"><p className="text-5xl font-semibold text-blue-400/25">{num}</p><h3 className="mt-3 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></div>)}</div></Section>

    <section className="mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-20"><div className="grid overflow-hidden rounded-3xl border border-blue-400/15 bg-gradient-to-br from-blue-500/13 to-slate-900/30 lg:grid-cols-2"><div className="p-7 sm:p-10"><p className="text-sm font-medium text-blue-300">More than a line on your resume</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white">A program that leaves you with momentum.</h2><p className="mt-4 leading-7 text-slate-300">Learn the rhythms of modern product teams while developing the judgment and confidence employers notice.</p></div><div className="grid gap-3 p-7 sm:grid-cols-2 sm:p-10">{benefits.map(([Icon,text]) => <div key={text} className="flex items-center gap-3 rounded-xl border border-white/8 bg-[#0d172c]/70 p-4 text-sm font-medium text-slate-200"><Icon className="size-5 text-blue-300"/>{text}</div>)}</div></div></section>

    <Section id="stories" eyebrow="Student stories" title="Built to make a difference you can feel."><div className="grid gap-5 lg:grid-cols-3">{[["‘The weekly feedback gave me the clarity I needed to finally ship work I was proud to show.’","Aarav Sharma","B.Tech, Delhi"],["‘I went from nervous about interviews to having three projects I could explain with confidence.’","Nisha Patel","BCA, Ahmedabad"],["‘It felt like joining a product team, not just another online course. That changed everything.’","Karan Mehta","B.Sc CS, Pune"]].map(([quote,name,meta]) => <figure key={name} className="rounded-2xl border border-white/8 bg-white/[.025] p-6"><div className="text-lg tracking-widest text-blue-300">★★★★★</div><blockquote className="mt-4 text-[15px] leading-7 text-slate-200">{quote}</blockquote><figcaption className="mt-6 border-t border-white/8 pt-4"><p className="text-sm font-medium">{name}</p><p className="mt-1 text-xs text-slate-500">{meta}</p></figcaption></figure>)}</div></Section>

    <Section id="faq" eyebrow="Questions, answered" title="Everything you need to know before you launch."><div className="mx-auto max-w-3xl divide-y divide-white/8 rounded-2xl border border-white/8 bg-white/[.025] px-5">{faqs.map(([q,a]) => <details key={q} className="group py-1"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-5 text-sm font-medium text-white"><span>{q}</span><ChevronDown className="size-4 text-blue-300 transition group-open:rotate-180"/></summary><p className="pb-5 text-sm leading-6 text-slate-400">{a}</p></details>)}</div></Section>

    <section className="mx-auto max-w-7xl px-5 pb-20 pt-8 lg:px-8 lg:pb-28"><div className="relative overflow-hidden rounded-3xl border border-blue-400/20 bg-blue-600 px-6 py-12 text-center sm:px-12"><Layers3 className="absolute -right-8 -top-8 size-48 rotate-12 text-white/10"/><p className="relative text-sm font-medium text-blue-100">Your next chapter starts here</p><h2 className="relative mx-auto mt-3 max-w-xl text-3xl font-semibold tracking-tight text-white sm:text-4xl">Ready to turn your ambition into experience?</h2><p className="relative mx-auto mt-4 max-w-lg text-sm leading-6 text-blue-100">Join a focused community of students building the confidence to take their next opportunity.</p><Link href="/apply" className="relative mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-blue-700 shadow-lg transition hover:bg-blue-50">Apply to InternLaunch <ArrowRight className="size-4"/></Link></div></section>
  </main>;
}

function Section({ eyebrow, title, copy, children, id }: { eyebrow: string; title: string; copy?: string; children: ReactNode; id?: string }) { return <section id={id} className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="mb-10 max-w-2xl"><p className="text-sm font-medium text-blue-300">{eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">{title}</h2>{copy && <p className="mt-4 leading-7 text-slate-400">{copy}</p>}</div>{children}</section> }
